name: QuIC Organization Repolinter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  repolinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Repolinter
        run: npm install -g repolinter

      - name: Ensure ruleset exists
        shell: bash
        run: |
          if [ ! -f "repolint.json" ]; then
            curl -fsSL "https://raw.githubusercontent.com/quic/.github/main/repolint.json" -o repolint.json
          fi

      - name: Run Repolinter
        run: repolinter . --ruleset ./repolint.json
